import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="" style={{ scrollBehavior: "smooth" }} lang="en">
      <body className={inter.className}>
        {children}
        <ToastContainer position="bottom-center" />
      </body>
    </html>
  );
}
